FROM ubuntu:23.10

RUN apt-get update && apt-get -y install --no-install-recommends build-essential libfuse3-dev libcap-dev libzstd-dev cmake git ca-certificates autoconf automake libtool && rm -rf /var/lib/apt/lists/*
