FROM alpine:edge

RUN apk add g++ cmake make git zlib autoconf libtool automake pkgconfig zstd-dev xz-dev zstd zstd-static fuse3-dev fuse3-static lz4-dev lz4-static lzo-dev xz-dev xz-static zlib-dev zlib-static libcap-dev libcap-static dpkg

