name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xqms/tiny_runtime_build:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          args:
            - "CMAKE_BUILD_TYPE=RelWithDebInfo"
          run-build: true
      - uses: actions/upload-artifact@v4
        with:
          name: tiny_runtime
          path: build/tiny_runtime
