name: Build and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xqms/tiny_runtime_build:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Configure
        run: cmake '.' -B 'build' -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - name: Build
        run: cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: tiny_runtime
          path: build/tiny_runtime
